### ISSUE TITLE
IC event listeners discarded when Datatables draws table

### ISSUE THREAD

**Issue by abcflorida** [bigskysoftware/intercooler-js#249]
IC events are not being added to DT rows that are not shown.  The first page has them, but not others.  I cannot apply IC to those rows unless I wait until drawn, but this causes duplicate handlers on all the previous rows.

There doesn't seem to be a refresh options, or remove option.

**Comment by baumann74** [comment]
@abcflorida I have a feeling it is related to this unresolved issue: https://github.com/LeadDyno/intercooler-js/issues/215. It also only work the first time.

**Comment by abcflorida** [comment]
So, I can attach the IC handlers if I use IC.processNodes(".myclass") after initialization of bootstrap.  However, this attaches 2 handlers to the first page which results in 2 requests to the endpoint for DT page results....  I can't seem to "unset" and "reinitialize" IC on the class manually....  I can only "Add" via processNodes().  Is there a way to do this?  I mean to kill the IC handlers and reapply them on the DOM?

**Comment by carsongross** [comment]
Hi @abcflorida yeah, it is kinda gnarly when you have dynamic HTML: you need to listen for DOM mutations and then process the new stuff.  This is highly library dependent though.  :/

A cleaner solution would be to make processNodes() not re-initialize already initialized stuff.  I will add that to the list of things I need to do.

**Comment by abcflorida** [comment]
Cool, that would be great.  In this instance, I can let it reinitialize...  Whats weird though is that those extra listeners dont stack after multiple actions... Just dups the one time.

So, I did use this to work on just the elements that are new :
 $(".triggerAdModal").on("success.ic", function ( evt, elt, data, textStatus, xhr, requestId ) { 
                // we need to wait until the data has processed.  Use the promise to do this??
                $.when( xhr ).done( function ( data ) { 
                     //apply things on the new DOM elements
                    $(data).each( function (i, obj ) {
                       
                       InterCooler.processNodes($(obj).prop('id'));
                       
                    }
                });                              
});

**Comment by abcflorida** [comment]
I wanted to thank you for this.  I never got back to you  after you fixed it.  Works great!

**Comment by 1cg** [comment]
:)
