### ISSUE TITLE
New add-object form includes a  dependent select

### ISSUE THREAD

**Issue by DNWEIJ** [bigskysoftware/intercooler-js#324]
Hi there, 

Thanks for making a very good library!! :-) 

I have a question about form processing:
I have a form for a new object that contains some fields and a dependent dropdown list (http://intercoolerjs.org/examples/dependentselect.html). A simple code version of my form added below. 

It is not working as I would expected. 
I was expecting, then the 2e dropdown would be populated with the dropdown element selected from the 1e dropdown, via the backend call.  Instead the  form is executed on return. 

When i remove the outer form tag  (where class="form-horizontal")  everything works as expected.  The dropdown selection result is populated in the 2e dropdown. 

When i put back the outer form tag, the  "ic-on-success" on the outer form is executed. 
When i remove the "ic-on-success" (but leave the outer form tag), the returned data isn't placed in the select, but replaces the select and the options are shown as a list on the screen. 
When i remove the  ic-target="#content" from the form, then it works BUT my form submission (the actual form submission i want to submit the fields i have plus the two dropdown selections) isn't working.

So the question i have is: how can i have a form that contains a dependent dropdown and still have a ic-on-success and a ic-replace-target  on the form?
 
Is this possible?

added:
I did a bit of code research and it seems there is no indication of this 'special' case where you essentially do a tiny snippet replacement, the options.
Since this is indeed a handy way of using intercooler to also load data for the 'pending on other' use case, i would say this is in a preparation fase and thus should not do the normal form processing, but just the replacement and not look for ic-on-success etc. 
Reason why i say this, is that it also works WITHOUT a form tag. 

added:
Looking at the example again from dependentselect.html i see that actually the javscript code is doing, what i want to do with the intercooler form properties. 

Regards, 
Daniël

```
form class="form-horizontal"  ic-on-success="$('#edit').hide();" ic-post-to="/new/object" ic-target="#content" ic-replace-target="true">

            <select class="form-control" name="templateId" ic-post-to="/list/data" ic-target="#add" ic-indicator="#add-ind">
                    <option value="1" >option1</option>
            </select>
            <select id="add" class="form-control" name="add">
                <option selected value="">No Data</option>
            </select>

            <button class="btn btn-default btn-primary">Submit</button>
            <a class="btn btn-outline-info" onclick="$('#edit').hide();">Cancel</a>
</form>
```

**Comment by jvosloo** [comment]
I think you need to add a ic-on-success handler on the master (templateId) select as well, because when the ic-post-to fires on change, the select inherits the ic-on-success event handler from the form, so to speak. You can see the behavior described in the documentation here: http://intercoolerjs.org/attributes/ic-on-success.html at the bottom.

You may need to override other properties as well on the master select (e.g. ic-deps="false"), if applicable.

**Comment by DNWEIJ** [comment]
Hi!
I see what you mean. 
I will try that as soon as i can. 

However, it seems strange that the immediate form around the dropdown isn't used and that the ic-on-succes is used of the global. 
I would expect that the immedita form with:
`ic-post-to="/list/data" ic-target="#add" ic-indicator="#add-ind"`
is enough to execute and replace the information to the dropdown (this is also working standalone, without the global form)
and feels strange that from the immediate form, it bubbles up to the global form to execute the `ic-on-success`

So it isn't bound to the first found form...

regards, Daniël
