### ISSUE TITLE
intercooler-1.1.1.min.js offline

### ISSUE THREAD

**Issue by SoltauFintel** [bigskysoftware/intercooler-js#327]
"https://intercoolerreleases-leaddynocom.netdna-ssl.com/intercooler-1.1.1.min.js" can not be reached!

**Comment by adamstep** [comment]
It seems like all HTTPS links on the download page are not working: https://intercoolerjs.org/download.html

The two newest versions (1.2.3 and 1.2.2) are not affected, they're not using `https://intercoolerreleases-leaddynocom.netdna-ssl.com` but rather `http://cdn.intercoolerjs.org`.

@1cg any idea what's going on? Can older releases be served from `http://cdn.intercoolerjs.org`?

**Comment by SoltauFintel** [comment]
I switched to 1.2.3. I hope this version is compatible. Also, I've now embedded the file in my JAR.

**Comment by 1cg** [comment]
Hi there.

Very sorry about that, unfortunately maxcdn reneg'd on providing free CDN services for intercooler.

You can link the older file directly now (it's hosted on netlify): 

https://intercoolerjs.org/release/intercooler-1.1.1.min.js

or, better, use a NPM based CDN like jsdeliver:

https://cdn.jsdelivr.net/npm/intercooler@1.1.1/dist/intercooler.min.js

I regret taking maxcdns offer up and doubly regret directly linking to their CDN.  :(
