### ISSUE TITLE
ic-trigger-from not working on form with ic-post-to

### ISSUE THREAD

**Issue by raffaeletani** [bigskysoftware/intercooler-js#335]
I have multiple forms on one page wich i'd like to submit all at once by clicking on one button.

the forms have _ic-post-to_ and _ic-trigger-from="#myButton"_ set.
but when i  click the button, no form gets posted.

is this intended behaviour?

**Comment by adamstep** [comment]
Hi @raffaeletani ,

I think you will find `ic-include` will do what you want. On your button, you can add this attribute with selectors for the forms on the page. All of that data will be included in the request: https://intercoolerjs.org/attributes/ic-include.html
